bot:
  name: becomeChampionBot
  token: ${TOKEN_BECOME_CHAMPION_BOT}

app:
  admin-id: ${ADMIN_CHAT_ID}

spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver