bot:
  name: becomeChampionBot
  token: ${TOKEN_BECOME_CHAMPION_BOT}

app:
  admin-id: 238349375

spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  config: classpath:log4j.properties